<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>limon</AssemblyName>
	<ApplicationIcon>limon.ico</ApplicationIcon>
    <Product>limon</Product>
    <Company>b1no</Company>
    <Authors>b1no</Authors>
	<Publisher>b1no</Publisher>
    <Copyright>© 2026 b1no. All rights reserved</Copyright>
  	<AssemblyVersion>4.6.0</AssemblyVersion>
    <FileVersion>4.6.0</FileVersion>
  	<Version>4.6.0</Version>
    <InformationalVersion>Stable</InformationalVersion>
	<RepositoryUrl>https://github.com/Storinob/limon</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="done.wav" />
  </ItemGroup>
</Project>