name: Send Discord Release Announcement

on:
  release:
    types: [published, prereleased]

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: |
            @code-update
            # limon - ${{ github.event.release.name }}
            ${{ github.event.release.body }}

            https://github.com/Storinob/limon/releases/tag/${{ github.event.release.tag_name }}
